# workflow name

name: media_service_backend CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # docker container start
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build


      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # allow gradlew permission
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build and Test with Gradle
        run: ./gradlew --info build
